name: Run Unit Tests

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  DevOpsPRUnitTests:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Test
        run: |
          npm install
          npm test
