name: Run Unit Tests

on:
  pull_request:
    branches: [ "CI/CD" ]
  workflow_dispatch:
jobs:
  DevOpsPRUnitTests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Private Dependencies and Test
        run: |
          sudo apt install -y jq
          echo "@razroo:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GitHubToken }}" >> ~/.npmrc
          npm install
      - name: Test
        run: |
          yarn
          npm run test 
