name: Run Unit Tests

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
jobs:
  DevOpsPRUnitTests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          node-version: '16'
          cache: 'npm'
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Install Dependencies and Test
        run: |
          npm install 
          npm test